require: "ts-node/register/transpile-only"
color: true
recursive: true
bail: true
exit: true
timeout: 60000
#
# NOTE mocha ignores command line opts with this entry
#
# spec:
#   - src/**/*.spec.ts
#   - test/**/*ts
