env: NODE_ENV

host: HOST

auth:
  jwtSecret: JWT_SECRET

llmProxy:
  openai:
    apiKey: OPENAI_API_KEY
  anthropic:
    apiKey: ANTHROPIC_API_KEY
  vertex:
    projectId: VERTEX_PROJECT_ID
    location: VERTEX_LOCATION
    clientEmail: VERTEX_CLIENT_EMAIL
    privateKey: VERTEX_PRIVATE_KEY
  openrouter:
    apiKey: OPENROUTER_API_KEY
    baseUrl: OPENROUTER_BASE_URL

tokenAnalytics:
  langfuse:
    secretKey: LANGFUSE_SECRET_KEY
    publicKey: LANGFUSE_PUBLIC_KEY
    baseUrl: LANGFUSE_BASE_URL

mongodb:
  connectionString: MONGO_URL
  dbName: MONGO_DATABASE

rmq:
  connection:
    uri: RABBITMQ_URI
