env: development

auth:
  jwtSecret: "local"

llmProxy:
  openai:
    apiKey: "your-openai-api-key"
  anthropic:
    apiKey: "your-anthropic-api-key"
  vertex:
    projectId: "your-gcp-project-id"
    location: "us-central1"
    clientEmail: "your-gcp-client-email"
    privateKey: "your-gcp-private-key"
  openrouter:
    apiKey: "your-openrouter-api-key"
    baseUrl: "https://openrouter.ai/api/v1"
  freeModels: ["openrouter/google/gemma-3-4b-it", "text-embedding-3-small", "gpt-3.5-turbo", "gpt-4o-mini"]

tokenAnalytics:
  langfuse:
    secretKey: "your-langfuse-secret-key"
    publicKey: "your-langfuse-public-key"
    baseUrl: "https://cloud.langfuse.com"

http:
  port: 8080

mongodb:
  connectionString: "mongodb://localhost"
  dbName: "llm-proxy"
  options:
    directConnection: false
  collections:
    - name: users
      indexes:
        - keys:
            id: 1
          options:
            unique: true
            background: true
        - keys:
            'provider.email.id': 1
            'provider.visitor.id': 1
          options:
            unique: true
            background: true
        - keys:
            'provider.email.id': 1
          options:
            unique: false
            background: true
        - keys:
            'provider.visitor.id': 1
          options:
            unique: false
            background: true

rmq:
  connection:
    uri: "amqp://admin:admin@localhost:5672/"
    name: "llm-proxy"
  exchanges:
    - name: "fanout.auth.user.created"
      type: "fanout"
    - name: "fanout.auth.user.updated"
      type: "fanout"
    - name: "fanout.billing.credits.updated"
      type: "fanout"
