env: development

llmProxy:
  openai:
    apiKey: "your-openai-api-key"
  anthropic:
    apiKey: "your-anthropic-api-key"
  vertex:
    projectId: "your-gcp-project-id"
    location: "us-central1"
    clientEmail: "your-gcp-client-email"
    privateKey: "your-gcp-private-key"
  openrouter:
    apiKey: "your-openrouter-api-key"
    baseUrl: "https://openrouter.ai/api/v1"

tokenAnalytics:
  langfuse:
    secretKey: "your-langfuse-secret-key"
    publicKey: "your-langfuse-public-key"
    baseUrl: "https://cloud.langfuse.com"

http:
  port: 8080
