env: development

auth:
  jwtSecret: "local"

template:
  exampleConfigKey: "exampleConfigValue"

http:
  port: 8080

rmq:
  exchanges:
    - name: "fanout.auth.user.created"
      type: "fanout"
    - name: "fanout.auth.user.updated"
      type: "fanout"
    - name: "topic.from.service-name"
      type: "topic"
    - name: "topic.service-name.to"
      type: "topic"

mongodb:
  connectionString: "mongodb://mongodb"
  dbName: "template-api"
  options:
    maxConnecting: 50
    directConnection: false
  collections:
    - name: users
      indexes:
        - keys:
            id: 1
          options:
            unique: true
            background: true
        - keys:
            "provider.email.id": 1
            "provider.visitor.id": 1
          options:
            unique: true
            background: true
        - keys:
            "provider.email.id": 1
          options:
            unique: true
            background: true
            sparse: true
        - keys:
            "provider.visitor.id": 1
          options:
            unique: true
            background: true
            sparse: true
